require "active_support/all"

require "code_hunter/version"
require "code_hunter/config"
require "code_hunter/method_logger"
require "code_hunter/option_parser"
require "code_hunter/runner"
require "code_hunter/renderer"
require "code_hunter/pendaxes"
require "code_hunter/brakeman"
require "code_hunter/rails_best_practices"
require "code_hunter/git_blamer"
require "code_hunter/warning"
